/**
 * metadata.ts — Centralized metadata generation for all tool responses.
 *
 * Provides professional-use warnings, data freshness tracking, and source authority disclosure.
 */

import type { Database } from '@ansvar/mcp-sqlite';

export interface ResponseMetadata {
  /** Data freshness information */
  data_freshness: DataFreshness;

  /** Professional use disclaimer */
  disclaimer: string;

  /** Source authority disclosure */
  source_authority: SourceAuthority;

  /** Known coverage gaps */
  coverage_gaps: string[];

  /** EU AI Act transparency notice */
  ai_disclosure: string;

  /** Optional note (e.g. document resolution failure) */
  note?: string;

  /** Query strategy used (e.g. 'broadened', 'like_fallback') */
  query_strategy?: string;
}

export interface DataFreshness {
  /** Last database update timestamp */
  statute_last_updated: string | null;

  /** Last case law sync timestamp */
  case_law_last_sync: string | null;

  /** Warning if data appears stale (>30 days) */
  staleness_warning: string | null;
}

export interface SourceAuthority {
  /** Primary data source description */
  primary_source: string;

  /** Authority level assessment */
  authority_level: 'official' | 'community-maintained';

  /** Verification requirement */
  verification_required: string;
}

/**
 * Generate standard metadata for tool responses.
 *
 * This provides consistent professional-use warnings, data freshness tracking,
 * and source authority disclosure across all tools.
 *
 * @param db - Optional database handle. If not provided, data freshness checks are skipped.
 */
export function generateResponseMetadata(db?: Database): ResponseMetadata {
  const dataFreshness = db ? getDataFreshness(db) : getEmptyDataFreshness();
  const sourceAuthority = getSourceAuthority();

  return {
    data_freshness: dataFreshness,
    disclaimer: 'NOT LEGAL ADVICE. This tool is for research purposes only and does not constitute professional legal advice. Always verify citations with official sources before relying on them in legal matters. Users are solely responsible for verifying accuracy and currency of all information.',
    source_authority: sourceAuthority,
    coverage_gaps: [
      'Pre-2021 decisions (anonymization status varies; excluded from v0.1)',
      'Full verbatim decision text (HTML summary only; full text in linked PDF)',
      'Lagmannsrett and Tingrett decisions (not in v0.1 scope)',
      'Nynorsk and Sami language versions not separately indexed',
    ],
    ai_disclosure: 'AI-assisted legal research tool. Results generated by algorithmic search and may contain errors or omissions. Human review required before professional use.'
  };
}

/**
 * Return empty data freshness when database is not available.
 */
function getEmptyDataFreshness(): DataFreshness {
  return {
    statute_last_updated: null,
    case_law_last_sync: null,
    staleness_warning: 'Data freshness information unavailable (tool does not query database)'
  };
}

/**
 * Check data freshness and generate staleness warnings.
 */
function getDataFreshness(db: Database): DataFreshness {
  // Check decisions last_updated
  let decisionsLastUpdated: string | null = null;
  try {
    const row = db.prepare(`
      SELECT MAX(last_updated) as max_date
      FROM decisions
      WHERE last_updated IS NOT NULL
    `).get() as { max_date: string | null } | undefined;
    decisionsLastUpdated = row?.max_date || null;
  } catch {
    // Ignore errors (table may not exist)
  }

  // Check db_metadata for build timestamp
  let dbBuiltAt: string | null = null;
  try {
    const metaRow = db.prepare(
      "SELECT value FROM db_metadata WHERE key = 'built_at'"
    ).get() as { value: string } | undefined;
    dbBuiltAt = metaRow?.value || null;
  } catch {
    // Ignore errors
  }

  const lastSync = decisionsLastUpdated || dbBuiltAt;
  const stalenessWarning = calculateStalenessWarning(lastSync, null);

  return {
    statute_last_updated: lastSync,
    case_law_last_sync: lastSync,
    staleness_warning: stalenessWarning,
  };
}

/**
 * Generate staleness warning if data is >30 days old.
 */
function calculateStalenessWarning(
  statuteDate: string | null,
  caseLawDate: string | null
): string | null {
  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

  const warnings: string[] = [];

  if (statuteDate) {
    const statuteTimestamp = new Date(statuteDate);
    if (statuteTimestamp < thirtyDaysAgo) {
      const daysOld = Math.floor((now.getTime() - statuteTimestamp.getTime()) / (24 * 60 * 60 * 1000));
      warnings.push(`Statute data is ${daysOld} days old - amendments may have been published`);
    }
  } else {
    warnings.push('Statute update timestamp unavailable');
  }

  if (caseLawDate) {
    const caseLawTimestamp = new Date(caseLawDate);
    if (caseLawTimestamp < thirtyDaysAgo) {
      const daysOld = Math.floor((now.getTime() - caseLawTimestamp.getTime()) / (24 * 60 * 60 * 1000));
      warnings.push(`Case law data is ${daysOld} days old - new decisions may be missing`);
    }
  }

  return warnings.length > 0 ? warnings.join('. ') : null;
}

/**
 * Get source authority disclosure.
 */
function getSourceAuthority(): SourceAuthority {
  return {
    primary_source: 'domstol.no (Norwegian Courts Administration) — post-2021 Høyesterett decisions, pre-anonymized per domstol.no publication policy, copyright-exempt under åndsverkloven §14.',
    authority_level: 'official',
    verification_required: 'ALWAYS verify case numbers against domstol.no before citing in professional legal work. The database contains HTML summary descriptions, not full verbatim court decisions. Full decisions are available via the linked PDF on each result.'
  };
}

/**
 * Wrapper type for tool responses that includes metadata.
 */
export interface ToolResponse<T> {
  /** Tool-specific results */
  results: T;

  /** Professional-use metadata and warnings */
  _meta: ResponseMetadata;

  /** Citation metadata for deterministic citation pipeline (optional) */
  _citation?: import('./citation.js').CitationMetadata;

  /** Truncation hint (optional) */
  _truncated?: boolean;
  _hint?: string;
}
